accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('signup/blogger/', views.signup_blogger, name='signup_blogger'),
    path('signup/reader/', views.signup_reader, name='signup_reader'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('reset/', auth_views.PasswordResetView.as_view(
        template_name='password_reset.html',
        email_template_name="password_reset_email.html",
        subject_template_name='password_reset_subject.txt'
    ),
         name='password_reset'),
    path('reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='password_reset_done.html'),
         name='password_reset_done'

         ),
    path('reset/<str:uidb64>/<str:token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='password_reset_confirm.html'),
         name='password_reset_confirm'
         ),
    path('reset/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='password_reset_complete.html'),
         name='password_reset_complete'
         ),
    path('settings/password/', auth_views.PasswordChangeView.as_view(
        template_name='password_change.html'),
         name='password_change'
         ),
    path('settings/account/', views.UserUpdateView.as_view(), name='my_account'),
    path('contact/', views.contact, name='contact'),
]

SOCIAL_AUTH_URL_NAMESPACE = "social"

boards/urls.py
from django.conf import settings
from django.urls import path
from django.conf.urls.static import static

from . import views


app_name = 'boards'
urlpatterns = [
    path('', views.BoardListView.as_view(), name='home'),
    path('create/', views.board_create, name='board_create'),
    path('<int:pk>/update/', views.board_update, name='board_update'),
    path('<int:pk>/delete/', views.board_delete, name='board_delete'),
    path('<int:pk>/', views.TopicListView.as_view(), name='board_topics'),
    path('<int:pk>/new/', views.new_topic, name='new_topic'),
    path('<int:pk>/topics/<int:topic_pk>/', views.PostListView.as_view(), name='topic_posts'),
    path('<int:pk>/topics/<int:topic_pk>/reply', views.reply_topic, name='reply_topic'),
    path('<int:pk>/topics/<int:topic_pk>/posts/<int:post_pk>/edit/', views.PostUpdateView.as_view(), name='edit_post'),
    path('<int:pk>/topics/<int:topic_pk>/to_csv/', views.export_topic_csv, name="to_csv"),
    path('<int:pk>/topics/<int:topic_pk>/to_pdf/', views.export_topic_pdf, name="to_pdf"),
    path('upload/photos/<pk>/', views.photo_create, name='basic_upload'),
    # path('<int:pk>/topics/<int:topic_pk>/gallery/', views.gallery_images, name="gallery_images"),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include
from django.urls import path
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('boards/', include('boards.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/settings/password/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='password_change_done.html'),
         name='password_change_done'
         ),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns += [
#         path('debug/', include(debug_toolbar.urls)),
#
#     ]

boards/forms.py
from django import forms

from .models import Board, Post, Topic, Image  # , Photo


# from django.core.files import File
# from PIL import Image


class NewTopicForm(forms.ModelForm):
    message = forms.CharField(
        widget=forms.Textarea(
            attrs={'rows': 5, 'placeholder': 'What is on your mind?'}
        ),
        max_length=4000,
        help_text='The max length of the text is 4000.'
    )
    file_field = forms.FileField(widget=forms.FileInput(attrs={'multiple': True,
                                                               'onchange': 'readURL(this);',
                                                               'accept': ".jpg, .jpeg, .png",
                                                               }), required=False)

    class Meta:
        model = Topic
        exclude = ('views', 'board', 'starter')



class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['message']


class BoardForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ('name', 'description')


class PhotoForm(forms.ModelForm):
    file_field = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))
    # file_field = forms.FileField(required=False, widget=forms.FileInput(attrs={
    #     'multiple': True,
    #     'class': 'js-upload-photos',
    #     'id': 'fileupload',
    # }))

    class Meta:
        model = Image
        fields = ('file_field', )


# class GalleryImagesForm(forms.ModelForm):
#     class Meta:
#         model = GalleryImages
#         fields = ('file', )


# class PhotoForm(forms.ModelForm):
#     x = forms.FileField(widget=forms.HiddenInput())
#     y = forms.FileField(widget=forms.HiddenInput())
#     width = forms.FileField(widget=forms.HiddenInput())
#     height = forms.FileField(widget=forms.HiddenInput())
#
#     class Meta:
#         model = Photo
#         fields = ('file', 'x', 'y', 'width', 'height', )
#
#     def save(self, commit=True):
#         photo = super(PhotoForm, self).save()
#
#         x = self.cleaned_data.get('x')
#         y = self.cleaned_data.get('y')
#         w = self.cleaned_data.get('width')
#         h = self.cleaned_data.get('height')
#
#         image = Image.open(photo.file)
#         cropped_image = image.crop((x, y, w+x, h+y))
#         resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
#         resized_image.save(photo.file.path)
#
#         return photo

boards/views.py
import csv

from django.contrib.admin.models import LogEntry
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage
from django.db.models import Count
from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render, reverse
from django.template.loader import render_to_string
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.generic import ListView, UpdateView


from weasyprint import HTML

# from django.contrib import messages

from .forms import BoardForm, NewTopicForm, PostForm, PhotoForm
from .models import Board, Post, Topic, Image


class BoardListView(ListView):
    model = Board
    context_object_name = 'boards'
    template_name = 'home.html'
    paginate_by = 20
    queryset = Board.objects.filter(is_active=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['history'] = Board.history.all()
        return context


def save_board_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            board = Board.objects.all()
            data['html_partial_board'] = render_to_string('includes/partial_board.html', {
                'boards': board,
                'user': request.user
            })
        else:
            data['form_is_valid'] = False
    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)


@login_required
def board_create(request):
    if request.method == 'POST':
        form = BoardForm(request.POST)
    else:
        form = BoardForm()
    return save_board_form(request, form, 'board_create.html')


@login_required
def board_update(request, pk):
    board = get_object_or_404(Board, pk=pk)
    if request.method == "POST":
        form = BoardForm(request.POST, instance=board)
    else:
        form = BoardForm(instance=board)
    return save_board_form(request, form, 'board_update.html')


@login_required
def board_delete(request, pk):
    board = get_object_or_404(Board, pk=pk)
    data = dict()
    boards = Board.objects.all()
    if request.method == 'POST':
        board.delete()
        data['form_is_valid'] = True
        data['html_partial_board'] = render_to_string('includes/partial_board.html', {
            'boards': boards,
            'user': request.user
        })
    else:
        context = {'boards': board}
        data['html_form'] = render_to_string('board_delete.html',
                                             context,
                                             request=request,
                                             )
    return JsonResponse(data)


class TopicListView(ListView):
    model = Topic
    context_object_name = 'topics'
    template_name = 'topics.html'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        kwargs['board'] = self.board
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        self.board = get_object_or_404(Board, pk=self.kwargs.get('pk'))
        queryset = self.board.topics.order_by('-last_update').annotate(replies=Count('posts') - 1)
        return queryset


@login_required
def new_topic(request, pk):
    board = get_object_or_404(Board, pk=pk)
    if request.method == "POST":
        form = NewTopicForm(request.POST)
        if form.is_valid():
            topic = form.save(commit=False)
            topic.board = board
            topic.starter = request.user
            topic.save()
            Post.objects.create(
                message=form.cleaned_data.get('message'),
                topic=topic,
                created_by=request.user
            )
            files = request.FILES.getlist('file_field')
            for file in files:
                request.FILES['file_field'] = file
                photos_form = PhotoForm(request.POST, request.FILES)
                if photos_form.is_valid():
                    photos_objects = photos_form.save(commit=False)
                    photos_objects.topic = topic
                    photos_objects.save()

            return redirect('boards:topic_posts', pk=pk, topic_pk=topic.pk)
        else:
            return render(request, 'new_topic.html', {'form': form, 'board': board})

    else:
        form = NewTopicForm()
    return render(request, 'new_topic.html', {'form': form, 'board': board})


class PostListView(ListView):
    model = Post
    context_object_name = 'posts'
    template_name = 'topic_posts.html'
    paginate_by = 20

    def get_context_data(self, **kwargs):
        session_key = 'viewed_topic_{}'.format(self.topic.pk)
        if not self.request.session.get(session_key, False):
            self.topic.views += 1
            self.topic.save()
            self.request.session[session_key] = True

        kwargs['topic'] = self.topic
        res = super().get_context_data(**kwargs)
        photos = res.get('topic').photos
        res.update({'photos': photos})
        return res

    def get_queryset(self):
        self.topic = get_object_or_404(Topic, board__pk=self.kwargs.get('pk'), pk=self.kwargs.get('topic_pk'))
        queryset = self.topic.posts.order_by('created_at')
        return queryset


@login_required
def reply_topic(request, pk, topic_pk):
    topic = get_object_or_404(Topic, board__pk=pk, pk=topic_pk)
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.topic = topic
            post.created_by = request.user
            post.save()

            topic.last_update = timezone.now()
            topic.save()

            topic_url = reverse('boards:topic_posts', kwargs={'pk': pk, 'topic_pk': topic_pk})
            topic_post_url = '{url}?page={page}#{id}'.format(
                url=topic_url,
                id=post.pk,
                page=topic.get_page_count()
            )

            return redirect(topic_post_url)
        else:
            return render(request, 'reply_topic.html', {'topic': topic, 'form': form})
    else:
        form = PostForm()
    return render(request, 'reply_topic.html', {'topic': topic, 'form': form})


@method_decorator(login_required, name='dispatch')
class PostUpdateView(UpdateView):
    model = Post
    fields = ('message',)
    template_name = 'edit_post.html'
    pk_url_kwarg = 'post_pk'
    context_object_name = 'post'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(created_by=self.request.user)

    def form_valid(self, form):
        post = form.save(commit=False)
        post.update_by = self.request.user
        post.update_at = timezone.now()
        post.save()
        return redirect('boards:topic_posts', pk=post.topic.board.pk, topic_pk=post.topic.pk)


def export_topic_csv(request, pk, topic_pk):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="topic.csv"'

    writer = csv.writer(response)
    writer.writerow(['Author', 'Message', 'Date'])

    posts = Post.objects.filter(topic=Topic.objects.get(pk=topic_pk)).values_list('topic', 'message', 'created_at')

    for post in posts:
        writer.writerow(post)

    return response


def export_topic_pdf(request, pk, topic_pk):
    topic = Topic.objects.get(pk=topic_pk)
    posts = Post.objects.filter(topic=topic)
    board = topic.board
    html_string = render_to_string(
        'topic_posts_to_pdf.html', {'posts': posts, 'topic': topic, 'board': board})

    html = HTML(string=html_string)
    html.write_pdf(target='/tmp/mypdf.pdf')

    fs = FileSystemStorage('/tmp')
    with fs.open('mypdf.pdf') as pdf:
        response = HttpResponse(pdf, content_type='application/pdf')
        response['Content-Disposition'] = 'attachment; filename="mypdf.pdf"'
        return response



def photo_create(request, pk):
    data = dict()
    board = Board.objects.get(pk=pk)
    if request.method == "POST":
        photo = request.FILES.get('file')
        data = {'is_valid': True, 'name': photo.file.name, 'url': photo.file.name}
        return JsonResponse(data)







# def gallery_images(request, pk, topic_pk):
#     topic = Topic.objects.get(pk=topic_pk)
#     if request.method == "POST":
#         form = GalleryImagesForm(request.POST, request.FILES)
#         if form.is_valid():
#             image = form.save(commit=False)
#             image.topic = topic
#             image.save()
#         else:
#             form = GalleryImagesForm()
#     else:
#         form = GalleryImagesForm()
#     images = GalleryImages.objects.filter(topic=topic).order_by('-created_at')
#     return render(request, 'gallery_images.html', {'images': images, 'topic': topic, 'form': form})

templates/base_accounts.html
{% extends 'base.html' %}

{% load static %}
{% load flatpages %}
{% get_flatpages as flatpages %}


{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block body %}
  <div class="container" style="margin-bottom: 100px;">
   {% if messages %}
    <div class="alert alert-success">
    {% for m in messages %}
        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ m }}</li>
    {% endfor %}
    </div>
    {% endif %}
    <h1 class="text-center logo my-4">
      <a href="{% url 'boards:home' %}">Django Boards</a>
    </h1>
      {% block content %}
      {% endblock %}
  </div>

  <footer class="footer">
      <p class="text-center text-light">
      ©Django Boards. All Rights Reserved | Design by Danil Kolodyazhny<br>
      <a href="/pages/policy/">Privacy Policy</a> /
      <a href="/pages/terms/">Terms</a>
    </p>
    </footer>

{% endblock %}

templates/choose_role.html
{% extends 'base_accounts.html' %}

{% block title %}Choose your role {% endblock %}

{% block content %}
  <div class="text-center  thead-dark  card-footer bg-light">
  <h2 class="text-center">Choose role.</h2>
  <p class="lead text-center">Select below the type of account you want to create</p>
  <a href="{% url 'accounts:signup_blogger' %}" class="btn btn-primary  " role="button">I'm a Blogger</a>
  <a href="{% url 'accounts:signup_reader' %}" class="btn btn-primary "  role="button">I'm a Reader</a>
  </div>
     <div class="card-footer text-muted text-center bg-light">
          Already have an account? <a href="{% url 'accounts:login' %}">Log in</a>
        </div>
{% endblock %}

templates/gallery_images.html
{% extends 'base.html' %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'boards:home' %}">Boards</a></li>
  <li class="breadcrumb-item"><a href="{% url 'boards:board_topics' topic.board.pk %}">{{ topic.board.name }}</a></li>
  <li class="breadcrumb-item"><a href="{% url 'boards:topic_posts' topic.board.pk topic.pk %}">{{ topic.subject }}</a></li>
  
{% endblock %}
{% block content %}
<form  method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {% include 'includes/form.html' %}
  <button type='submit' class='btn btn-success'>Add image</button>
</form>

<div class="d-flex flex-wrap justify-content-start">
{% for image in images %}
<div class="gallery-image-item m-2">
  <img class="img-fluid img-thumbnail" src="{{image.image.url}}" alt="">
</div>
{% endfor %}
</div>

{% endblock %}

templates/login.html
{% extends 'base_accounts.html' %}

{% block title %}Log in to Django Boards{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Log in</h3>
          <form method="post" novalidate>
            {% csrf_token %}
             <input type="hidden" name="next" value="{{ next }}">
            {% include 'includes/form.html' %}

               <script src='https://www.google.com/recaptcha/api.js'></script>
              <div class="g-recaptcha" data-sitekey="6Ld1p5UbAAAAAHmsIGf4qWV3fNiHgNnM4tq6mrZ5"></div>
            <button type="submit" class="btn btn-primary btn-block">Log in</button>
          </form>
             <div class="row text-center">
    <div class="col-md-8 mx-auto social-container my-2 order-md-1">
        <button class="btn mb-1 m-md-1 ">

            <a href="{% url 'social:begin' 'github' %}">Login with Github</a>
        </button>
        <button class="btn ">
            <a href="{% url 'social:begin' 'google-oauth2' %}">Login with Google
            </a>
        </button>

    </div>
</div>
        </div>
        <div class="card-footer text-muted text-center">
          New to Django Boards? <a href="{% url 'accounts:signup' %}">Sign up</a>
        </div>
      </div>
      <div class="text-center py-2">
        <small>
          <a href="{% url 'accounts:password_reset' %}" class="text-muted">Forgot your password?</a>
        </small>
      </div>
    </div>
  </div>
{% endblock %}

templates/new_topic.html
{% extends 'base.html' %}

{% load widget_tweaks %}
{% load static %}

{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/fileinput.css' %}">
{% endblock %}

{% block title %}Start a New Topic{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'boards:home' %}">Boards</a></li>
    <li class="breadcrumb-item"><a href="{% url 'boards:board_topics' board.pk %}">{{ board.name }}</a></li>
    <li class="breadcrumb-item active">New topic</li>
{% endblock %}

{% block content %}
    <form method="post" novalidate enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="js-upload-photos btn btn-success mb-2">Post</button>

    </form>


    <table id="my_photo"></table>



    {% include 'photos.html' %}

    {% block javascript %}

        <script src="{% static 'js/jquery.ui.widget.js' %}"></script>
        <script src="{% static 'js/jquery.iframe-transport.js' %}"></script>
        <script src="{% static 'js/jquery.fileupload.js' %}"></script>
        <script src="{% static 'js/basic-upload.js' %}"></script>
          <script type="text/javascript">
            function readURL(input) {
                console.log('i am pressed');
                let table = document.getElementById("gallery");
                table.innerHTML = "";
                for (let i = 0; i < input.files.length; i++) {
                var newRow = table.insertRow(0);

                // Insert a cell in the row at index 0
                var newCell = newRow.insertCell(0);
                var img = document.createElement("img");
                img.classList.add("obj");
                img.file = input.files[i];
                newCell.appendChild(img);

                // Append a text node to the cell
                var newText = document.createTextNode(input.files[i].name);
                newCell.appendChild(newText);
            }
            }
</script>





{#         <script type="text/javascript">#}
{#            function readURL(input) {#}
{#                console.log(input);#}
{##}
{#                let table = document.getElementById("gallery");#}
{#                table.innerHTML = "";#}
{#                for (let i = 0; i < input.files.length; i++) {#}
{#                    var newRow = table.insertRow(0);#}
{##}
{#                    // Insert a cell in the row at index 0#}
{#                    var newCell = newRow.insertCell(0);#}
{#                    var img = document.createElement("img");#}
{#                    img.classList.add("obj");#}
{#                    img.file = input.files[i];#}
{#                    img.style.height = "100px"#}
{##}
{#                    // Append a text node to the cell#}
{#                    var newText = document.createTextNode(input.files[i].name);#}
{#                    var newTextName = newText.data.split(" ").join("_")#}
{#                    img.src = `http://mysite.ua:8000/media/gallery_topics/${newTextName}`#}
{#                    newCell.appendChild(img);#}
{##}
{#                    var cell = `${newCell.innerHTML}#}
{#                        <a#}
{#                            href="http://mysite.ua:8000/media/gallery_topics/${newTextName}"#}
{#                            target="_blank"#}
{#                        >#}
{#                            ${newTextName}#}
{#                        </a>`;#}
{##}
{#                    newCell.innerHTML = cell;#}
{#                }#}
{#            }#}
{#        </script>#}
    {% endblock %}


{% endblock %}




{##}
{#{% extends 'base.html' %}#}
{#{% load widget_tweaks static %}#}
{#{% block javascript %}#}
{# <script src="{% static 'js/jquery.ui.widget.js' %}"></script>#}
{#        <script src="{% static 'js/jquery.iframe-transport.js' %}"></script>#}
{#        <script src="{% static 'js/jquery.fileupload.js' %}"></script>#}
{#        <script src="{% static 'js/basic-upload.js' %}"></script>#}
{#        <script src="{% static 'js/progress-bar-upload.js' %}"></script>#}
{#{% endblock %}#}
{#{% block title %}Start a New Topic{% endblock %}#}
{#{% block breadcrumb %}#}
{#<li class="breadcrumb-item"><a href="{% url 'boards:home' %}">Boards</a></li>#}
{#<li class="breadcrumb-item"><a href="{% url 'boards:board_topics' board.pk %}">{{ board.name }}</a></li>#}
{#<li class="breadcrumb-item active">New topic</li>#}
{#{% endblock %}#}
{#{% block content %}#}
{#{%comment%}#}
{#<form method="post" novalidate>#}
{#    {% csrf_token %}#}
{#    {% for field in form %}#}
{#      <div class="form-group">#}
{#        {{ field.label_tag }}#}
{#        {% if form.is_bound %}#}
{#          {% if field.errors %}#}
{#            {% render_field field class="form-control is-invalid" %}#}
{#            {% for error in field.errors %}#}
{#              <div class="invalid-feedback">#}
{#                {{ error }}#}
{#              </div>#}
{#            {% endfor %}#}
{#          {% else %}#}
{#            {% render_field field class="form-control is-valid" %}#}
{#          {% endif %}#}
{#        {% else %}#}
{#          {% render_field field class="form-control" %}#}
{#        {% endif %}#}
{#        {% if field.help_text %}#}
{#          <small class="form-text text-muted">#}
{#            {{ field.help_text }}#}
{#          </small>#}
{#        {% endif %}#}
{#      </div>#}
{#    {% endfor %}#}
{#    <button type="submit" class="btn btn-success">Post</button>#}
{#  </form>#}
{#{%endcomment%}#}
{#<div style="margin-bottom: 20px;">#}
{#<form method="POST" enctype="multipart/form-data">#}
{#  {% csrf_token %}#}
{#  {% include 'includes/form.html' %}#}
{#  <!-- <button type="button" class="btn btn-primary js-upload-photos">#}
{#    <span class="glyphicon glyphicon-cloud-upload"></span> Upload photos#}
{#  </button> -->#}
{#</div>#}
{#<button type="submit" class="btn btn-success mb-5">POST</button>#}
{#</form>#}
{#<table id="gallery" class="table table-bordered ">#}
{#  <thead>#}
{#    <tr>#}
{#      <th>Photo</th>#}
{#    </tr>#}
{#  </thead>#}
{#  <tbody>#}
{#    {% for photo in photos %}#}
{#      <tr>#}
{#        <td><a href="{{ photo.file_field.url }}">{{ photo.file_field.name }}</a></td>#}
{#      </tr>#}
{#    {% endfor %}#}
{#  </tbody>#}
{#</table>#}
{#<div class="modal fade" id="modal-progress" data-backdrop="static" data-keyboard="false">#}
{#  <div class="modal-dialog">#}
{#    <div class="modal-content">#}
{#      <div class="modal-header">#}
{#        <h4 class="modal-title">Uploading...</h4>#}
{#      </div>#}
{#      <div class="modal-body">#}
{#        <div class="progress">#}
{#          <div class="progress-bar" role="progressbar" style="width: 0%;">0%</div>#}
{#        </div>#}
{#      </div>#}
{#    </div>#}
{#  </div>#}
{#</div>#}
{#{% endblock %}#}

templates/photos.html
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Uploaded Photos</th>
    </tr>
  </thead>
  <tbody id="gallery">
  </tbody>
</table>

templates/topic_posts.html
{% extends 'base.html' %}

{% load static %}

{% block title %}{{ topic.subject }}{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'boards:home' %}">Boards</a></li>
  <li class="breadcrumb-item"><a href="{% url 'boards:board_topics' topic.board.pk %}">{{ topic.board.name }}</a></li>
  <li class="breadcrumb-item active">{{ topic.subject }}</li>
{% endblock %}

{% block content %}


    <div class="mb-4 ">
    <a href="{% url 'boards:reply_topic' topic.board.pk topic.pk %}" class="btn btn-primary" role="button">Reply</a>
     <a href="{% url 'boards:to_csv' topic.board.pk topic.pk %}"  class="btn btn-primary">Import CSV</a>
     <a href="{% url 'boards:to_pdf' topic.board.pk topic.pk %}"  class="btn btn-primary">Import PDF</a>
    </div>
    <div class="mb-4 text-right">

    </div>

  {% for post in posts %}
      <input id="fileupload" type="file" name="file" multiple
       style="display: none;"
       data-url="{% url 'boards:basic_upload' post.topic.pk%}"
       data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>





    <div id="{{ post.pk }}" class="card {% if forloop.last %}mb-4{% else %}mb-2{% endif %} {% if forloop.first %}border-dark{% endif %}">
      {% if forloop.first %}
        <div class="card-header text-white bg-dark py-2 px-3">{{ topic.subject }}</div>

            rewwev
        <img src="/{{post.file_field}}" class="img-thumbnail" style="height: 200px;" alt="">

      {% endif %}

      <div class="card-body p-3">
        <div class="row">
          <div class="col-2">
            <img src="{% static 'img/avatar.svg' %}" alt="{{ post.created_by.username }}" class="w-100">
            <small>Posts: {{ post.created_by.posts.count }}</small>
          </div>
          <div class="col-10">
            <div class="row mb-3">
              <div class="col-6">
                <strong class="text-muted">{{ post.created_by.username }}</strong>
              </div>
              <div class="col-6 text-right">
                <small class="text-muted">{{ post.created_at }}</small>
              </div>
            </div>
            {{ post.get_message_as_markdown }}
            {% if post.created_by == user %}
              <div class="mt-3">
                <a href="{% url 'boards:edit_post' post.topic.board.pk post.topic.pk post.pk %}"
                   class="btn btn-primary btn-sm"
                   role="button">Edit</a>
              </div>
            {% endif %}

          </div>
        </div>
      </div>
    </div>
  {% endfor %}

  {% include 'includes/pagination.html' %}
{% endblock %}